# Generated by Django 2.2.1 on 2019-05-24 15:24

from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='source',
            field=models.ForeignKey(default=main.models.default_source, on_delete=django.db.models.deletion.CASCADE, to='main.Source'),
        ),
    ]
