# Generated by Django 2.2.1 on 2019-05-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190524_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('slug', models.SlugField(max_length=256, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='passage',
            name='modified',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='passage',
            name='tags',
            field=models.ManyToManyField(to='main.Tag'),
        ),
    ]
