# Generated by Django 2.2.1 on 2019-06-04 05:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinged', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('first_name', models.CharField(blank=True, max_length=256)),
                ('last_name', models.CharField(blank=True, max_length=256)),
                ('aka', models.ManyToManyField(blank=True, related_name='_author_aka_+', to='main.Author')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinged', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Medium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'media',
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinged', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinged', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('color', models.CharField(blank=True, max_length=64)),
                ('description', models.TextField(blank=True)),
                ('pinned', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinged', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('publication', models.CharField(blank=True, max_length=256)),
                ('url', models.URLField(blank=True, max_length=256)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('authors', models.ManyToManyField(to='main.Author')),
                ('medium', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Medium')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('owner', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Passage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('pinged', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('body', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('is_starred', models.BooleanField(default=False)),
                ('is_refreshable', models.BooleanField(default=False)),
                ('in_trash', models.BooleanField(default=False)),
                ('collections', models.ManyToManyField(blank=True, to='main.Collection')),
                ('origin', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Origin')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passages', to=settings.AUTH_USER_MODEL)),
                ('source', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Source')),
                ('tags', models.ManyToManyField(blank=True, to='main.Tag')),
                ('topics', models.ManyToManyField(blank=True, to='main.Topic')),
            ],
            options={
                'unique_together': {('owner', 'uuid')},
            },
        ),
    ]
